import { DataSource } from "typeorm";
import {
  Clinics,
  Doctors,
  Doses,
  DrugForms,
  Drugs,
  Durations,
  Frequencyes,
  MealTimings,
  Methods,
  Patients,
  PrescriptionItems,
  Prescriptions,
  Quantityes,
  Users,
} from "./entities";

export const AppDataSource = new DataSource({
  type: "postgres",
  host: process.env.DB_HOST,
  port: Number(process.env.DB_PORT) || 5432,
  username: process.env.DB_USERNAME,
  database: process.env.DB_DATABASE,
  password: process.env.DB_PASSWORD,
  entities: [
    Users,
    Patients,
    Drugs,
    DrugForms,
    Doses,
    Methods,
    Doctors,
    Clinics,
    Durations,
    Frequencyes,
    MealTimings,
    Quantityes,
    Prescriptions,
    PrescriptionItems,
  ],
  synchronize: true,
});
